import type { Ani4uStreamServer } from "@/lib/ani4u-stream";
import type { EpisodeServer, PlaybackType } from "@/lib/api";

export type UnifiedServer =
  | { id: string; name: string; source: "fansub"; type: "direct" | "iframe" | "hls"; url: string; server: Ani4uStreamServer }
  | { id: string; name: string; source: "legacy" | "witanime"; type: PlaybackType; server: EpisodeServer };

function fansubId(server: Ani4uStreamServer) {
  // Two Google Drive files can share source and host, so the validated URL is
  // part of the stable selector identity.
  return `fansub:${server.source}:${server.host}:${server.url}`;
}

function playbackKey(url: string) {
  const parsed = new URL(url);
  const port = parsed.port && parsed.port !== "443" ? `:${parsed.port}` : "";
  return `https://${parsed.hostname.toLowerCase()}${port}${parsed.pathname || "/"}${parsed.search}`;
}

export function mergeStreamServers(fansub: Ani4uStreamServer[], legacy: EpisodeServer[], witanime: EpisodeServer[] = []): UnifiedServer[] {
  const seenUrls = new Set<string>();
  const preferred: Extract<UnifiedServer, { source: "fansub" }>[] = fansub.filter((server) => {
    const key = playbackKey(server.url);
    if (seenUrls.has(key)) return false;
    seenUrls.add(key);
    return true;
  }).map((server) => ({
    id: fansubId(server), name: `Fansub · ${server.host}`, source: "fansub", type: server.type, url: server.url, server,
  }));
  const sourceServers = (servers: EpisodeServer[], source: "legacy" | "witanime") => servers.filter((server) => {
    // Similar server names are never evidence of a duplicate. A normalized
    // exact public URL is the only deduplication key.
    if (!server.embedUrl) return false;
    const key = playbackKey(server.embedUrl);
    if (seenUrls.has(key)) return false;
    seenUrls.add(key);
    return true;
  }).map((server, index): Extract<UnifiedServer, { source: "legacy" | "witanime" }> => ({
    id: `${source}:${server.name}:${server.id || index}`, name: server.name, source, type: server.type || "iframe", server,
  }));
  return [...preferred, ...sourceServers(legacy, "legacy"), ...sourceServers(witanime, "witanime")];
}

export function selectStreamServer(servers: UnifiedServer[], requested?: string) {
  return (requested && servers.find((server) => server.id === requested))
    // Maintain compatibility with links generated by the prior server selector.
    || (requested && servers.find((server) => server.source === "legacy" && server.server.name === requested))
    || servers[0];
}
